### ISSUE TITLE
Yslow Error

### ISSUE THREAD

**Issue by pragmaticivan** [keepfast/keepfast-cli#3]
```
λ pragmaticivan [pragmaticivan/opensource/elixir-school] at  master ✔
→ keepfast https://elixirschool.com                                                                                        [653c7fb]
------------------------------------------------------------------------

🚀  Plugin: keepfast-contrib-psi 🌎  URL: https://elixirschool.com

  ⚠️  Warnings (average is related to alexa top 1000 sites)

    🐢  PageSpeed Score: 86  (should be > 90)

  👍  Already done!


------------------------------------------------------------------------

🚀  Plugin: keepfast-contrib-phantomas 🌎  URL: https://elixirschool.com

  ⚠️  Warnings (average is related to alexa top 1000 sites)

    🐢  Number of web font responses: 4  (should be < 3.1)
    🐢  Number of <img> nodes without both width and height attribute: 2  (should be = 0)
    🐢  Static assets that were not gzipped: 1  (should be = 0)

  👍  Already done!

    😀  Number of HTTP 404 responses: 0
    😀  Total number of HTTP requests: 15
    😀  Total number of HTTPS requests: 14
    😀  Size of the content of all responses: 59168 bytes
    😀  Size of the content of all responses: 59168 bytes
    😀  Number of HTML responses: 1
    😀  Size of HTML responses: 9772 bytes
    😀  Number of CSS responses: 2
    😀  Size of CSS responses: 9485 bytes
    😀  Number of JS responses: 3
    😀  Size of JS responses: 21698 bytes
    😀  Number of image responses: 3
    😀  Size of image responses: 10034 bytes
    😀  Size of web font responses: 8157 bytes
    😀  Number of other responses: 1
    😀  Size of other responses: 1 bytes
    😀  Total number of HTML element nodes: 110 elements
    😀  Maximum level on nesting of HTML element node: 7
    😀  Number of duplicated IDs found in DOM: 0
    😀  Number of domains used to fetch the page: 8
    😀  Maximum number of requests fetched from a single domain: 4
    😀  The size of body tag content (document.body.innerHTML.length): 7884 bytes



┌────────────────────────────────────────────┐
│ Update available: 0.0.13 (current: 0.0.11) │
│ Run npm install -g keepfast-cli to update. │
└────────────────────────────────────────────┘

Error: Error parsing results from https://elixirschool.com
    at Object.YSlow.runSync (/usr/local/lib/node_modules/keepfast-cli/node_modules/yslowjs/lib/yslow.js:45:19)
    at /usr/local/lib/node_modules/keepfast-cli/node_modules/keepfast-contrib-yslow/index.js:16:27
    at tryCatcher (/usr/local/lib/node_modules/keepfast-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/keepfast-cli/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/keepfast-cli/node_modules/bluebird/js/release/promise.js:554:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/keepfast-cli/node_modules/bluebird/js/release/promise.js:591:10)
    at Async._drainQueue (/usr/local/lib/node_modules/keepfast-cli/node_modules/bluebird/js/release/async.js:130:12)
    at Async._drainQueues (/usr/local/lib/node_modules/keepfast-cli/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/keepfast-cli/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by davidsonfellipe** [comment]
@pragmaticivan thanks!
